web:
  build: .
  ports:
   - "5555:5000"
  links:
   - redis
  volumes:
   - .:/var/www/app

executer:
  build: ./executer
  links:
   - redis
  volumes:
   - ./:/var/www/app

  environment:
    C_FORCE_ROOT: "true"

redis:
  image: redis:3.0.7
